version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Mount the SQLite database file to persist data
      - sqlite_data:/app/data
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    networks:
      - app-network

volumes:
  sqlite_data:
    driver: local

networks:
  app-network:
    driver: bridge